// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Models;

namespace WebApplication1.Migrations
{
    [DbContext(typeof(UsuarioContext))]
    [Migration("20190515171848_add-Id_Phot-to-UserItem")]
    partial class addId_PhottoUserItem
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplication1.Models.PhotoItem", b =>
                {
                    b.Property<long>("IdPhoto")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("Imagem");

                    b.Property<string>("Name");

                    b.HasKey("IdPhoto");

                    b.ToTable("PhotoItem");
                });

            modelBuilder.Entity("WebApplication1.Models.UserFriends", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("IdFriends");

                    b.Property<long>("IdUser");

                    b.HasKey("Id");

                    b.HasIndex("IdUser");

                    b.ToTable("UserFriends");
                });

            modelBuilder.Entity("WebApplication1.Models.UserItem", b =>
                {
                    b.Property<long>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("Id_Photo");

                    b.Property<string>("Name");

                    b.Property<string>("Senha");

                    b.HasKey("IdUser");

                    b.ToTable("UserItems");
                });

            modelBuilder.Entity("WebApplication1.Models.UserFriends", b =>
                {
                    b.HasOne("WebApplication1.Models.UserItem", "UserItem")
                        .WithMany("Friends")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
